name: Checkov action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    env:
      PRISMA_API_URL: https://api4.prismacloud.io
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: './terraform/aws/s3.tf'
          soft_fail: true
          api-key: ${{ secrets.BC_API_KEY }}
      - name: Expose report
        uses: actions/upload-artifact@v2
        with:
          name: SARIF results
          path: results.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
